# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# Disable triggering when a PR is created
pr: none

trigger:
  tags:
    include:
    - '*.*.*-alpha.*'
    - '*.*.*-beta.*'
    - '*.*.*-rc.*'
    - '*.*.*'
    - 'v*.*.*'

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '3c90d7b9-95d9-4a67-aa95-33ae6de45469'
  containerRegistry: 'vianaacr.azurecr.io'

  imageRepositoryServer: 'cvat/server'
  dockerfilePathServer: '$(Build.SourcesDirectory)/Dockerfile'

  imageRepositoryUI: 'cvat/ui'
  dockerfilePathUI: '$(Build.SourcesDirectory)/Dockerfile.ui'

  tag: '$(Build.SourceBranchName)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: BuildAndPush
  displayName: Build and Push Images
  jobs:
  - job: BuildAndPushServer
    displayName: Build and push server image
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push server image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepositoryServer)
        dockerfile: $(dockerFilePathServer)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

  - job: BuildAndPushUI
    displayName: Build and push UI image
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push UI image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepositoryUI)
        dockerfile: $(dockerfilePathUI)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
