# Disable triggering CI build through PR
pr: none

trigger:
# Will trigger when tags are in the ff. forms:
#   1. v1.0.0-alpha.1+outcome
#   2. v1.0.0-beta+outcome
#   3. v1.0.0+outcome
# Won't trigger when tags are missing the '+' build suffix e.g.
#   v1.0.0-alpha, v1.0.0-beta.1 or v1.0.0
  tags:
    include:
      - v*.*.*+*

variables:
  DOCKER_BUILDKIT: 1
  REGISTRY_SERVICE_CONNECTION: 3c90d7b9-95d9-4a67-aa95-33ae6de45469
  DOCKERFILE_SERVER: $(Build.SourcesDirectory)/Dockerfile
  REPOSITORY_SERVER: cvat/server
  DOCKERFILE_UI: $(Build.SourcesDirectory)/Dockerfile.ui
  REPOSITORY_UI: cvat/ui

pool:
# Using the same Ubuntu version as specified in Dockerfile
  vmImage: ubuntu-22.04

stages:
- stage: A
  displayName: Derive image tag version
  jobs:
  - job: A1
    displayName: Derive image tag version job
    steps:
    - bash: |
        BRANCH=$(Build.SourceBranchName)  # Tag that triggered the build
        VERSION=${BRANCH#v}               # Remove the "v" prefix from tag
        VERSION=${VERSION%+*}             # Remove the "+*" suffix from tag

        echo "BRANCH is: $BRANCH"
        echo "VERSION is: $VERSION"

        echo "##vso[task.setvariable variable=version;isOutput=true]$VERSION"
      name: ImageTag
      displayName: Derive image tag version from branch name
- stage: B
  displayName: Build and push images
  dependsOn: A
  variables:
    TAG_VERSION: $[stageDependencies.A.A1.outputs['ImageTag.version']]
  jobs:
  - job: B1
    displayName: Build and push server image job
    steps:
    - bash: |
        echo $(REPOSITORY_SERVER):$(TAG_VERSION)
      displayName: Sanity check -- echo repository and tag
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: $(REPOSITORY_SERVER)
        dockerfile: $(DOCKERFILE_SERVER)
        containerRegistry: $(REGISTRY_SERVICE_CONNECTION)
        tag: |
          $(TAG_VERSION)
      displayName: Build and push server image task
  - job: B2
    displayName: Build and push UI image job
    steps:
    - bash: |
        echo $(REPOSITORY_PORTAL):$(TAG_VERSION)
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: $(REPOSITORY_UI)
        dockerfile: $(DOCKERFILE_UI)
        containerRegistry: $(REGISTRY_SERVICE_CONNECTION)
        tag: |
          $(TAG_VERSION)
      displayName: Build and push UI image task
